"""Authentication CLI commands for ACF Local Edition.

Configure API keys for marketplace access.
"""

import os
from pathlib import Path
from typing import Optional

import typer
from rich.console import Console

console = Console()

auth_app = typer.Typer(
    name="auth",
    help="Manage authentication and API keys for marketplace access.",
)


def get_config_dir() -> Path:
    """Get the config directory path."""
    config_dir = Path.home() / ".coding-factory"
    config_dir.mkdir(parents=True, exist_ok=True)
    return config_dir


def get_config_file() -> Path:
    """Get the config.env file path."""
    return get_config_dir() / "config.env"


def load_config() -> dict[str, str]:
    """Load config from config.env file."""
    config_file = get_config_file()
    config = {}
    if config_file.exists():
        for line in config_file.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                key, value = line.split("=", 1)
                config[key.strip()] = value.strip()
    return config


def save_config(config: dict[str, str]) -> None:
    """Save config to config.env file."""
    config_file = get_config_file()
    lines = [
        "# ACF Local Edition Configuration",
        "# Generated by 'acf auth login'",
        "",
    ]
    for key, value in sorted(config.items()):
        lines.append(f"{key}={value}")
    config_file.write_text("\n".join(lines) + "\n")


def validate_api_key(key: str) -> bool:
    """Validate API key format and verify against marketplace API.

    Returns True if key is valid and authenticated, False otherwise.
    """
    # Check format: acf_sk_ followed by 64 hex characters
    if not key.startswith("acf_sk_"):
        return False

    key_part = key[7:]  # Remove "acf_sk_" prefix
    if len(key_part) != 64:
        return False

    # Check if remaining part is valid hex
    try:
        int(key_part, 16)
    except ValueError:
        return False

    # Verify against marketplace API
    try:
        import httpx

        marketplace_url = os.environ.get(
            "ACF_MARKETPLACE_URL",
            "https://marketplace.agentcodefactory.com/api/v1"
        )
        with httpx.Client(timeout=10.0) as client:
            response = client.get(
                f"{marketplace_url}/me",
                headers={"Authorization": f"Bearer {key}"},
            )
            return response.status_code == 200
    except Exception:
        # If we can't connect, accept the key (offline mode)
        return True


@auth_app.command("login")
def login(
    key: Optional[str] = typer.Option(
        None,
        "--key",
        "-k",
        help="Your API key (starts with acf_sk_)",
    ),
) -> None:
    """Configure API key for marketplace access.

    To get your API key:
      1. Sign in at https://agentcodefactory.com/login.html
      2. Go to https://agentcodefactory.com/settings.html
      3. Create a new API key and copy it

    Examples:
        acf auth login --key acf_sk_abc123...
        acf auth login  # Interactive prompt
    """
    # Prompt for key if not provided
    if not key:
        console.print("[bold]Configure Marketplace API Key[/bold]\n")
        console.print("To get your API key:")
        console.print("  1. Sign in at: https://agentcodefactory.com/login.html")
        console.print("  2. Go to: https://agentcodefactory.com/settings.html")
        console.print("  3. Create a new API key and copy it\n")
        key = typer.prompt("Enter your API key")

    # Validate format
    if not key.startswith("acf_sk_"):
        console.print("[red]Invalid key format.[/red]")
        console.print("API keys should start with 'acf_sk_'")
        console.print("Create a new key at: https://agentcodefactory.com/settings.html")
        raise typer.Exit(1)

    # Test the key
    console.print("Validating API key...")
    if not validate_api_key(key):
        console.print("[red]API key validation failed.[/red]")
        console.print("The key may be invalid or expired.")
        console.print("Create a new key at: https://agentcodefactory.com/settings.html")
        raise typer.Exit(1)

    # Save to config
    config = load_config()
    config["ACF_MARKETPLACE_API_KEY"] = key
    save_config(config)

    console.print(f"\n[green]API key saved to {get_config_file()}[/green]")
    console.print("\nYou can now install paid extensions with:")
    console.print("  acf marketplace install <extension-name>")


@auth_app.command("logout")
def logout() -> None:
    """Remove stored API key.

    Example:
        acf auth logout
    """
    config = load_config()

    if "ACF_MARKETPLACE_API_KEY" not in config:
        console.print("[yellow]No API key configured.[/yellow]")
        return

    del config["ACF_MARKETPLACE_API_KEY"]
    save_config(config)

    console.print("[green]API key removed.[/green]")


@auth_app.command("status")
def status() -> None:
    """Show current authentication status.

    Example:
        acf auth status
    """
    # Check environment variable first
    env_key = os.environ.get("ACF_MARKETPLACE_API_KEY")
    if env_key:
        masked = f"{env_key[:10]}...{env_key[-4:]}" if len(env_key) > 14 else "***"
        console.print(f"[green]Authenticated via environment variable[/green]")
        console.print(f"  Key: {masked}")
        return

    # Check config file
    config = load_config()
    config_key = config.get("ACF_MARKETPLACE_API_KEY")

    if config_key:
        masked = f"{config_key[:10]}...{config_key[-4:]}" if len(config_key) > 14 else "***"
        console.print(f"[green]Authenticated via config file[/green]")
        console.print(f"  Key: {masked}")
        console.print(f"  File: {get_config_file()}")
    else:
        console.print("[yellow]Not authenticated[/yellow]")
        console.print("\nTo configure your API key:")
        console.print("  1. Sign in at: https://agentcodefactory.com/login.html")
        console.print("  2. Go to: https://agentcodefactory.com/settings.html")
        console.print("  3. Create a new API key and copy it")
        console.print("  4. Run: acf auth login --key YOUR_KEY")
