"""Configuration layout schema.

Defines 12-factor style configuration management with
environment separation, feature flags, and secrets handling.
"""

from enum import Enum

from pydantic import BaseModel, Field


class ConfigType(str, Enum):
    """Type of configuration variable."""

    STRING = "string"
    INTEGER = "integer"
    FLOAT = "float"
    BOOLEAN = "boolean"
    LIST = "list"
    SECRET = "secret"
    URL = "url"
    PATH = "path"


class Environment(str, Enum):
    """Deployment environments."""

    DEVELOPMENT = "development"
    STAGING = "staging"
    PRODUCTION = "production"
    TEST = "test"


class ConfigCategory(str, Enum):
    """Categories of configuration."""

    DATABASE = "database"
    CACHE = "cache"
    API = "api"
    AUTH = "auth"
    LOGGING = "logging"
    FEATURE_FLAGS = "feature_flags"
    EXTERNAL_SERVICES = "external_services"
    APPLICATION = "application"
    SECRETS = "secrets"


class ConfigVariable(BaseModel):
    """A single configuration variable."""

    name: str = Field(..., description="Variable name (e.g., DATABASE_URL)")
    env_var: str = Field(..., description="Environment variable name")
    config_type: ConfigType = Field(..., description="Data type")
    category: ConfigCategory = Field(..., description="Configuration category")
    description: str = Field("", description="What this variable controls")
    required: bool = Field(True, description="Whether variable is required")
    is_secret: bool = Field(False, description="Whether this is a secret value")
    default_value: str | None = Field(None, description="Default value if not set")
    example_value: str | None = Field(None, description="Example value for docs")
    validation_pattern: str | None = Field(
        None, description="Regex pattern for validation"
    )


class EnvironmentOverride(BaseModel):
    """Environment-specific value override."""

    variable: str = Field(..., description="Variable name")
    environment: Environment = Field(..., description="Target environment")
    value: str = Field(..., description="Override value")
    description: str | None = Field(None, description="Why this override exists")


class FeatureFlag(BaseModel):
    """A feature flag configuration."""

    name: str = Field(..., description="Flag name (e.g., ENABLE_NEW_UI)")
    env_var: str = Field(..., description="Environment variable name")
    description: str = Field(..., description="What this flag controls")
    default_enabled: bool = Field(False, description="Default state")
    environments_enabled: list[Environment] = Field(
        default_factory=list,
        description="Environments where flag is enabled by default",
    )


class SecretVariable(BaseModel):
    """A secret that must be provided via environment."""

    name: str = Field(..., description="Secret name")
    env_var: str = Field(..., description="Environment variable name")
    description: str = Field(..., description="What this secret is for")
    required: bool = Field(True, description="Whether secret is required")
    rotation_recommended: bool = Field(
        False, description="Whether regular rotation is recommended"
    )
    source_hint: str | None = Field(
        None, description="Hint about where to get this secret"
    )


class GeneratedConfigFile(BaseModel):
    """A configuration file generated by the agent."""

    path: str = Field(..., description="Relative file path")
    content: str = Field(..., description="File content")
    description: str = Field(..., description="Purpose of this file")
    file_type: str = Field(..., description="Type: python, yaml, env, md")


class ConfigLayoutReport(BaseModel):
    """Report from the ConfigAgent."""

    # Variables detected/created
    variables: list[ConfigVariable] = Field(
        default_factory=list,
        description="All configuration variables",
    )
    feature_flags: list[FeatureFlag] = Field(
        default_factory=list,
        description="Feature flags",
    )
    secrets: list[SecretVariable] = Field(
        default_factory=list,
        description="Secret variables",
    )
    environment_overrides: list[EnvironmentOverride] = Field(
        default_factory=list,
        description="Per-environment overrides",
    )

    # Files generated
    files_generated: list[GeneratedConfigFile] = Field(
        default_factory=list,
        description="Configuration files created",
    )
    files_modified: list[str] = Field(
        default_factory=list,
        description="Existing files modified",
    )

    # Summary counts
    total_variables: int = Field(0, description="Total config variables")
    total_secrets: int = Field(0, description="Total secrets")
    total_feature_flags: int = Field(0, description="Total feature flags")
    environments_configured: list[Environment] = Field(
        default_factory=list,
        description="Environments with configuration",
    )

    # 12-factor compliance
    twelve_factor_compliant: bool = Field(
        False, description="Whether config follows 12-factor principles"
    )
    compliance_notes: list[str] = Field(
        default_factory=list,
        description="Notes about 12-factor compliance",
    )

    # README integration
    readme_section_added: bool = Field(
        False, description="Whether README was updated"
    )
    readme_section_content: str | None = Field(
        None, description="Content added to README"
    )

    # Summary
    summary: str = Field("", description="Human-readable summary")

    def update_counts(self) -> None:
        """Update summary counts."""
        self.total_variables = len(self.variables)
        self.total_secrets = len(self.secrets)
        self.total_feature_flags = len(self.feature_flags)

    class Config:
        json_schema_extra = {
            "example": {
                "total_variables": 12,
                "total_secrets": 3,
                "total_feature_flags": 2,
                "twelve_factor_compliant": True,
            }
        }
