"""Observability configuration schema.

Defines logging, metrics, and tracing configuration
for production-ready observability scaffolding.
"""

from enum import Enum

from pydantic import BaseModel, Field


class LogLevel(str, Enum):
    """Standard log levels."""

    DEBUG = "DEBUG"
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"


class LogFormat(str, Enum):
    """Log output formats."""

    JSON = "json"
    TEXT = "text"
    STRUCTURED = "structured"


class MetricsBackend(str, Enum):
    """Supported metrics backends."""

    PROMETHEUS = "prometheus"
    OPENTELEMETRY = "opentelemetry"
    STATSD = "statsd"
    NONE = "none"


class TracingBackend(str, Enum):
    """Supported tracing backends."""

    OPENTELEMETRY = "opentelemetry"
    JAEGER = "jaeger"
    ZIPKIN = "zipkin"
    NONE = "none"


class LoggingConfig(BaseModel):
    """Logging configuration."""

    level: LogLevel = Field(LogLevel.INFO, description="Default log level")
    format: LogFormat = Field(LogFormat.JSON, description="Log output format")
    include_timestamp: bool = Field(True, description="Include ISO timestamp")
    include_correlation_id: bool = Field(
        True, description="Include request correlation ID"
    )
    include_request_id: bool = Field(True, description="Include unique request ID")
    include_user_id: bool = Field(False, description="Include user ID if available")
    include_trace_id: bool = Field(True, description="Include trace ID for tracing")
    log_request_body: bool = Field(False, description="Log request bodies (careful!)")
    log_response_body: bool = Field(False, description="Log response bodies")
    mask_sensitive_fields: list[str] = Field(
        default_factory=lambda: ["password", "token", "secret", "api_key", "auth"],
        description="Fields to mask in logs",
    )
    max_body_length: int = Field(1000, description="Max body length to log")


class MetricsConfig(BaseModel):
    """Metrics configuration."""

    enabled: bool = Field(True, description="Enable metrics collection")
    backend: MetricsBackend = Field(
        MetricsBackend.PROMETHEUS, description="Metrics backend"
    )
    endpoint: str = Field("/metrics", description="Metrics endpoint path")
    include_default_metrics: bool = Field(
        True, description="Include default Python/framework metrics"
    )
    histogram_buckets: list[float] = Field(
        default_factory=lambda: [0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0],
        description="Histogram bucket boundaries for latency",
    )
    labels: list[str] = Field(
        default_factory=lambda: ["method", "endpoint", "status"],
        description="Default metric labels",
    )


class TracingConfig(BaseModel):
    """Distributed tracing configuration."""

    enabled: bool = Field(True, description="Enable distributed tracing")
    backend: TracingBackend = Field(
        TracingBackend.OPENTELEMETRY, description="Tracing backend"
    )
    service_name: str = Field("", description="Service name for traces")
    sample_rate: float = Field(1.0, description="Trace sampling rate (0.0-1.0)")
    propagate_headers: list[str] = Field(
        default_factory=lambda: ["X-Correlation-ID", "X-Request-ID", "traceparent"],
        description="Headers to propagate",
    )
    trace_db_queries: bool = Field(True, description="Trace database queries")
    trace_http_clients: bool = Field(True, description="Trace outgoing HTTP requests")
    trace_redis: bool = Field(False, description="Trace Redis operations")


class HealthEndpoint(BaseModel):
    """Health check endpoint configuration."""

    path: str = Field(..., description="Endpoint path")
    checks: list[str] = Field(
        default_factory=list, description="Health checks to perform"
    )
    include_details: bool = Field(True, description="Include check details in response")


class DashboardPanel(BaseModel):
    """A panel in a Grafana dashboard."""

    title: str = Field(..., description="Panel title")
    type: str = Field("graph", description="Panel type (graph, stat, table, etc.)")
    metric_query: str = Field(..., description="Prometheus query")
    description: str | None = Field(None, description="Panel description")


class GrafanaDashboard(BaseModel):
    """Grafana dashboard configuration."""

    title: str = Field(..., description="Dashboard title")
    description: str | None = Field(None, description="Dashboard description")
    refresh_interval: str = Field("5s", description="Auto-refresh interval")
    panels: list[DashboardPanel] = Field(
        default_factory=list, description="Dashboard panels"
    )


class GeneratedFile(BaseModel):
    """A file generated by the observability agent."""

    path: str = Field(..., description="Relative file path")
    content: str = Field(..., description="File content")
    description: str = Field(..., description="What this file does")


class ObservabilityReport(BaseModel):
    """Report from the ObservabilityAgent."""

    # Configuration used
    logging_config: LoggingConfig = Field(
        default_factory=LoggingConfig, description="Logging configuration"
    )
    metrics_config: MetricsConfig = Field(
        default_factory=MetricsConfig, description="Metrics configuration"
    )
    tracing_config: TracingConfig = Field(
        default_factory=TracingConfig, description="Tracing configuration"
    )

    # Framework detected
    framework: str = Field("unknown", description="Detected web framework")
    framework_version: str | None = Field(None, description="Framework version")

    # Files generated
    files_generated: list[GeneratedFile] = Field(
        default_factory=list, description="Files created"
    )
    files_modified: list[str] = Field(
        default_factory=list, description="Existing files modified"
    )

    # Health endpoints
    health_endpoints: list[HealthEndpoint] = Field(
        default_factory=list, description="Health check endpoints"
    )

    # Dashboard
    dashboard: GrafanaDashboard | None = Field(
        None, description="Generated Grafana dashboard"
    )
    dashboard_file: str | None = Field(
        None, description="Path to dashboard JSON file"
    )

    # Dependencies added
    dependencies_added: list[str] = Field(
        default_factory=list, description="Python packages to add"
    )

    # Summary
    summary: str = Field("", description="Human-readable summary")

    class Config:
        json_schema_extra = {
            "example": {
                "framework": "fastapi",
                "files_generated": [
                    {"path": "app/logging_config.py", "description": "JSON logging setup"}
                ],
                "dependencies_added": ["python-json-logger", "prometheus-client"],
            }
        }
